ALTER TABLE ip_pools ADD COLUMN vrf VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE ip_pools ADD COLUMN netmask VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE ip_pools ADD COLUMN nameservers TEXT[] NOT NULL DEFAULT '{}';
