ALTER TABLE ip_pools ADD COLUMN priority INT NOT NULL DEFAULT 0;
ALTER TABLE ip_pools ADD COLUMN rdns_server VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE ip_pools ADD COLUMN notes TEXT NOT NULL DEFAULT '';
ALTER TABLE ip_pools ADD COLUMN switch_automation BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE ip_pools ADD COLUMN vlan_id INT NOT NULL DEFAULT 0;
ALTER TABLE ip_pools ADD COLUMN vlan_range_start INT NOT NULL DEFAULT 0;
ALTER TABLE ip_pools ADD COLUMN vlan_range_end INT NOT NULL DEFAULT 0;
